<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

## Merging and Concatenation with numpy and pandas

_Authors: Kiefer Katovich (SF)_

---


### Learning Objectives
- Understand use-cases of concatenation of vectors, matrices, and dataframes
- Practice concatenating vectors and matrices using numpy
- Practice concatenating dataframes using pandas
- Join pandas dataframes using SQL-style join operations

### Lesson Guide
- [Overview of concatenation and joining](#introduction)
- [Concatenation using numpy](#numpy_concatenation)
- [Concatenation using pandas](#pandas_concatenation)
- [SQL-style joins using pandas](#pandas_joins)

<a id='introduction'></a>

### Overview of concatenation and joining

---

**Concatenation** is the process of joining separate objects along a dimension to create a new single object. In
computer programming and data processing, two or more character strings are sometimes concatenated for the purpose of saving space or so that they can be addressed as a single item.

In pandas, we will be concatenating dataframes together along rows or columns. Likewise, in numpy you can concatenate vectors and matrices along an axis.

**Joins** with pandas happen when columns of two DataFrames are joined together on index or on a key column. The concept is the same as SQL joins. In pandas, joins are done typically with the `.merge()` function. 

Here is a representation of left, right, inner, and outer joins with Venn diagrams:

![](./assets/joins.png)

<a id='numpy_concatenation'></a>

### Concatenation using numpy

---

Concatenating vectors and matrices in numpy is a common operation that is wise to practice. Because pandas uses numpy under the hood, concatenation in pandas is essentially equivalent to concatenation in numpy.


In [1]:
import numpy as np
import pandas as pd

In [2]:
vector1 = np.array([1,2,3,4])
vector2 = np.array([5,6,7,8])

#### Concatenate `vector1` and `vector2` together with `np.concatenate()`.

Note: unlike python lists, you cannot simply add two numpy vectors together and expect them to concatenate. The addition operator has a different meaning in numpy (element-wise addition).

In [4]:
# Concatenate the vectors
np.concatenate([vector1, vector2])

array([1, 2, 3, 4, 5, 6, 7, 8])

Our two arrays are 1-dimensional. We can make them 2-dimensional by adding an axis with `np.newaxis`. (One of the many ways to do this.)

#### Add a new axis to `vector1` to make it 2-dimensional. Print out the shape to verify.

In [9]:
print(vector1)

[1 2 3 4]


In [5]:
# Add a dimension to the vector
vect1_2d = vector1[:, np.newaxis]

In [7]:
print(vect1_2d, vect1_2d.shape)

[[1]
 [2]
 [3]
 [4]] (4, 1)


In [10]:
vect1_nd = vector1[np.newaxis, np.newaxis]
print(vect1_nd, vect1_nd.shape)

[[[1 2 3 4]]] (1, 1, 4)


There is a big difference between a vector of shape `(4,)` and another vector with shape `(4,1)`. Especially when it comes to matrix multiplications and linear algebra. Numpy prefers to operate with Vectors of shape `(R,1)` where `R` is Rows. 

[Here is a great answer to a question on StackOverflow explaining more on the topic.](http://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r)

Alternatively put the new axis in the first position:

In [11]:
# Add a dimension in another axis to the vector
vect1_row_dim = vector1[np.newaxis, :]

In [12]:
print(vector1, vector1.shape)

[1 2 3 4] (4,)


In [13]:
print(vect1_row_dim, vect1_row_dim.shape)

[[1 2 3 4]] (1, 4)


With 2D (and above) matrices concatenation must be done along an **axis**. With a two dimensional matrix you can think of concatenating along axis 0 as stacking vertically, and concatenation along axis 1 as stacking horizontally.

#### Make `vector1` and `vector2` 2D. Concatenate them vertically and horizontally by specifying the axis in the function.

In [15]:
# Make the vectors 2D and join them along both axes 
vect1_2d = vector1[np.newaxis, :]
vect2_2d = vector2[np.newaxis, :]

In [22]:
print("Vertical Stacking")
lst_data = np.concatenate([vect1_2d, vect2_2d], axis=0)
print(lst_data)

Vertical Stacking
[[1 2 3 4]
 [5 6 7 8]]


In [23]:
pd1 = pd.DataFrame(lst_data)

In [24]:
pd1

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [21]:
print("Horizontal Stacking")
print(np.concatenate([vect1_2d, vect2_2d], axis=1))

Horizontal Stacking
[[1 2 3 4 5 6 7 8]]


<a id='pandas_concatenation'></a>

### Concatenation using pandas

---

It is often the case that you  would like to concatenate two dataframes together. Perhaps your data is split up into two groups of subjects with the same variables/columns and you want to join them together (stacking vertically - adding rows). Or perhaps you have new variables for all of your existing subjects (stacking horizontally - adding columns).

Below we have two simple datasets we can use to practice pandas concatenation.

In [30]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']})

In [26]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [27]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [31]:
df3

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In pandas we can use the `pd.concat` function to stack DataFrames vertically or horizontally. `pd.concat()` takes a list of pandas dataframes as its first argument, and then an axis keyword argument indicating how to concatenate the dataframes. 

The axis argument works the same as in numpy.

**Concatenate `df1` and `df2` by stacking them vertically.**

In [28]:
# Vertical concatenation
pd.concat([df1, df2], axis=0)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

**Concatenate `df1` and `df2` by stacking them horizontally.**

In [29]:
# Horizontal concatenation
pd.concat([df1, df2], axis=1)

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [33]:
# Horizontal concatenation
pd.concat([df1, df2.reset_index(drop=True)], axis=1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [32]:
# Horizontal concatenation
pd.concat([df1, df3], axis=1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

You can see that because the pandas indice are different for the two dataframes, it fills in null values. Perhaps we don't care about the row labels during the horizontal concatenation. If you reset the index for `df2` prior to the concatenation it will not fill in null values:

In [ ]:
# Horizontal concatenation ignoring row labels


<a id='pandas_joins'></a>

### Left, right, inner, and outer joins in pandas

---

The pandas `merge` function allows us to join together DataFrames using columns as keys.

[(The same walkthrough can be found here.)](http://chrisalbon.com/python/pandas_join_merge_dataframe.html)

Below we have two dataframes with information on `subject_id`, `first_name`, and `last_name`. We also have a third dataframe with information on `subject_id` and `test_id`.

In [34]:
raw_data = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}
df_a = pd.DataFrame(raw_data)
df_a

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [35]:
raw_data = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
df_b = pd.DataFrame(raw_data)
df_b

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [37]:
raw_data = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
df_n = pd.DataFrame(raw_data)
df_n

subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

**Pandas `pd.merge()` for SQL-style joins**

A left join produces a complete set of records from `df_a`, with the matching records (where available) in `df_b`. If there is no match, the right side will contain null.

The pandas `pd.merge()` command has arguments:
- left-hand dataset
- right-hand dataset
- `on=` : keyword argument specifying the key column to join the dataframes on
- `how=` : keyword argument specifying the type of join (left, right, inner, outer)

#### Left join `df_b` onto `df_a` by `subject_id`.

In [43]:
df_merge = pd.concat([df_a, df_b])

In [46]:
df_merge

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [48]:
# left join
pd.merge(left=df_merge, right=df_n, on="subject_id", how="right")

subject_id first_name last_name  test_id
0           1       Alex  Anderson       51
1           2        Amy  Ackerman       15
2           3      Allen       Ali       15
3           4      Alice      Aoni       61
4           4      Billy    Bonder       61
5           5     Ayoung   Atiches       16
6           5      Brian     Black       16
7           7      Bryce     Brice       14
8           8      Betty    Btisan       15
9           9        NaN       NaN        1
10         10        NaN       NaN       61
11         11        NaN       NaN       16

#### Right join `df_b` onto `df_a` by `subject_id`

Merge with a right join produces a complete set of records from `df_b`, with the matching records (where available) in `df_a`. If there is no match, the left side will contain null.


In [60]:
pd.merge(left=df_b, right=df_a, how="right", on=df_a.index)

key_0 subject_id_x first_name_x last_name_x subject_id_y first_name_y  \
0      0            4        Billy      Bonder            1         Alex   
1      1            5        Brian       Black            2          Amy   
2      2            6         Bran     Balwner            3        Allen   
3      3            7        Bryce       Brice            4        Alice   
4      4            8        Betty      Btisan            5       Ayoung   

  last_name_y  
0    Anderson  
1    Ackerman  
2         Ali  
3        Aoni  
4     Atiches

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [52]:
# right join
pd.merge(left=df_b, right=df_a, how="right", left_index=True, right_index=True)

subject_id_x first_name_x last_name_x subject_id_y first_name_y last_name_y
0            4        Billy      Bonder            1         Alex    Anderson
1            5        Brian       Black            2          Amy    Ackerman
2            6         Bran     Balwner            3        Allen         Ali
3            7        Bryce       Brice            4        Alice        Aoni
4            8        Betty      Btisan            5       Ayoung     Atiches

In [57]:
df_a.join(df_b)

ValueError: columns overlap but no suffix specified: Index(['subject_id', 'first_name', 'last_name'], dtype='object')

#### Outer join `df_b` onto `df_a` by `subject_id`

An outer join produces the set of all records in `df_a` and `df_b`, with matching records from both sides where available. If there is no match, the missing side will contain null.

In [ ]:
# outer join

#### Inner join `df_b` onto `df_a` by `subject_id`

An inner join produces only the set of records that match in both df_a and df_b.

In [ ]:
# inner join

#### Combine the information in `df_a`, `df_b` and `df_n` using joins

No information should be lost.

In [61]:
df_a

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [62]:
df_b

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [63]:
df_n

subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

In [66]:
df_merge

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [67]:
# A:
pd.merge(left=df_merge, right=df_n, how = "outer", on="subject_id")

subject_id first_name last_name  test_id
0           1       Alex  Anderson     51.0
1           2        Amy  Ackerman     15.0
2           3      Allen       Ali     15.0
3           4      Alice      Aoni     61.0
4           4      Billy    Bonder     61.0
5           5     Ayoung   Atiches     16.0
6           5      Brian     Black     16.0
7           6       Bran   Balwner      NaN
8           7      Bryce     Brice     14.0
9           8      Betty    Btisan     15.0
10          9        NaN       NaN      1.0
11         10        NaN       NaN     61.0
12         11        NaN       NaN     16.0

#### Combine the information in the three datasets only where information is contained in all rows of the output.

In [ ]:
# A: 

In [73]:
tbl1 = pd.DataFrame({
    'User_id': [1,2,3],
    'Name': ['Batman', 'Joker', 'Tony Stark'],
    'DoB':['01/01/1974', '10/03/1959', '29/07/1984']
})
tbl1

User_id        Name         DoB
0        1      Batman  01/01/1974
1        2       Joker  10/03/1959
2        3  Tony Stark  29/07/1984

In [74]:
tbl1_temp = pd.DataFrame([[1, 'Batman', '01/01/1974'], [2, 'Joker', '10/03/1959'], [3, 'Tony Stark', '29/07/1984']])
tbl1_temp

0           1           2
0  1      Batman  01/01/1974
1  2       Joker  10/03/1959
2  3  Tony Stark  29/07/1984

In [75]:
tbl2 = pd.DataFrame({
    'User_id': [1,1,2,3,3],
    'Gift_Name': ['iPhone', 'Knife', 'batmobile', 'batmobile', 'suit'],
    'Gift_Category':['Accessory', 'Accessory', 'car', 'car', 'Accessory'],
    'Price':[10, 50, 100, 100, 1000]
})
tbl2

User_id  Gift_Name Gift_Category  Price
0        1     iPhone     Accessory     10
1        1      Knife     Accessory     50
2        2  batmobile           car    100
3        3  batmobile           car    100
4        3       suit     Accessory   1000

## Filter & Merge

### Filter, first

In [76]:
tbl1.DoB = pd.to_datetime(tbl1.DoB)

In [77]:
tbl1.head()

User_id        Name        DoB
0        1      Batman 1974-01-01
1        2       Joker 1959-10-03
2        3  Tony Stark 1984-07-29

In [78]:
tbl1_jan = tbl1[tbl1['DoB'].dt.month==1]
tbl1_jan

User_id    Name        DoB
0        1  Batman 1974-01-01

In [79]:
tbl_cars = tbl2[tbl2['Gift_Category']=='car']

In [80]:
tbl_cars

User_id  Gift_Name Gift_Category  Price
2        2  batmobile           car    100
3        3  batmobile           car    100

In [81]:
pd.merge(left = tbl1_jan, right= tbl_cars, how="inner", on="User_id")

Empty DataFrame
Columns: [User_id, Name, DoB, Gift_Name, Gift_Category, Price]
Index: []

In [82]:
tbl_name = tbl1[tbl1['Name']=='Tony Stark']

In [83]:
tbl_name

User_id        Name        DoB
2        3  Tony Stark 1984-07-29

In [84]:
tbl_suit = tbl2.loc[tbl2['Gift_Name']=='suit']

In [85]:
tbl_suit

User_id Gift_Name Gift_Category  Price
4        3      suit     Accessory   1000

In [88]:
pd.merge(left = tbl_name, right = tbl_suit, on="User_id", how="inner")['Price']

0    1000
Name: Price, dtype: int64